// config/planoSections.ts

export const planoSections = [
  /*-parte izquierda-*/
  { id: "A34", name: "Main Entrance" },
  { id: "A29", name: "Reception and waiting area" },
  { id: "A31", name: "Reception and waiting area" },
  { id: "A20", name: "Research and Development" },
  { id: "A30", name: "Cybersecurity" },
  { id: "A32", name: "Cybersecurity" },
  { id: "A33", name: "Advanced Robotics" },
  { id: "A16", name: "Artificial Intelligence" },
  { id: "A26", name: "Artificial Intelligence" },
  { id: "A21", name: "Special Projects Division lab" },
  { id: "A23", name: "Special Projects Division lab" },
  { id: "A17", name: "Software Engineering" },
  { id: "A22", name: "Software Engineering" },
  { id: "A14", name: "Networks and Communications" },
  { id: "A24", name: "Networks and Communications" },
  { id: "A04", name: "Systems Control" },
  { id: "A11", name: "Systems Control" },
  { id: "A12", name: "Logistics and Distribution" },
 /*-parte derecha-*/
  { id: "A05", name: "Chip and Processor Manufacturing" },
  { id: "A08", name: "Chip and Processor Manufacturing" },
  { id: "A06", name: "Autonomous Weapons Development" },
  { id: "A18", name: "Simulation and Training" },
  { id: "A19", name: "Simulation and Training" },
  { id: "A09", name: "Human resources" },
  { id: "A10", name: "Acquisitions and Contracts" },
  { id: "A13", name: "External Communications" },
  { id: "A15", name: "External Communications" },
  { id: "A27", name: "Quality Control" },
  { id: "A28", name: "Quality Control" },
  { id: "A25", name: "Nanobot Development" },
  { id: "A35", name: "Quantum Cryptography" },
  { id: "A36", name: "Quantum Cryptography" },
  { id: "A01", name: "Unloading Docks" },
  { id: "A02", name: "Unloading Docks" },
  { id: "A03", name: "Landing" },
];
